// <auto-generated />
using System;
using AuctionPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuctionPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20260622020134_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Imagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdSubasta")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("UrlAlmacenamiento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdSubasta");

                    b.ToTable("Imagenes", (string)null);
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Monedero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoComprometido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoDisponible")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Monederos", (string)null);
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.MovimientoMonedero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMonedero")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioAdmin")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdMonedero");

                    b.ToTable("MovimientosMonedero", (string)null);
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Leido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Notificaciones", (string)null);
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSubasta")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdSubasta", "Monto", "FechaHora");

                    b.ToTable("Pujas", (string)null);
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Comprador"
                        });
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAdminCreador")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioGanador")
                        .HasColumnType("int");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PujaMinima")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdAdminCreador");

                    b.HasIndex("IdUsuarioGanador");

                    b.ToTable("Subastas", (string)null);
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@subastas.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdRol = 1,
                            Nombre = "Admin",
                            PasswordHash = "$2a$12$LQv3c1yqBo9SkvXS7QTJPOeGxVdRZL7.GnXlJY1bVIYkh5JlsD1Vy"
                        });
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Imagen", b =>
                {
                    b.HasOne("AuctionPlatform.Domain.Entities.Subasta", "Subasta")
                        .WithMany("Imagenes")
                        .HasForeignKey("IdSubasta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Monedero", b =>
                {
                    b.HasOne("AuctionPlatform.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Monedero")
                        .HasForeignKey("AuctionPlatform.Domain.Entities.Monedero", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.MovimientoMonedero", b =>
                {
                    b.HasOne("AuctionPlatform.Domain.Entities.Monedero", "Monedero")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdMonedero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monedero");
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("AuctionPlatform.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Puja", b =>
                {
                    b.HasOne("AuctionPlatform.Domain.Entities.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("IdSubasta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuctionPlatform.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Pujas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subasta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Subasta", b =>
                {
                    b.HasOne("AuctionPlatform.Domain.Entities.Usuario", "AdminCreador")
                        .WithMany()
                        .HasForeignKey("IdAdminCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuctionPlatform.Domain.Entities.Usuario", "UsuarioGanador")
                        .WithMany()
                        .HasForeignKey("IdUsuarioGanador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdminCreador");

                    b.Navigation("UsuarioGanador");
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("AuctionPlatform.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Monedero", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Subasta", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("Pujas");
                });

            modelBuilder.Entity("AuctionPlatform.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Monedero")
                        .IsRequired();

                    b.Navigation("Notificaciones");

                    b.Navigation("Pujas");
                });
#pragma warning restore 612, 618
        }
    }
}
